# Generated by Django 6.1 on 2026-08-31 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('namespaces', '0002_namespace_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('replicas', models.IntegerField(default=1)),
                ('cpu', models.CharField(default='250m', max_length=20)),
                ('memory', models.CharField(default='256Mi', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleting', 'Deleting')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='namespaces.namespace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('namespace', 'name'), name='unique_app_per_namespace')],
            },
        ),
    ]
