# Generated by Django 6.1 on 2026-08-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namespaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deleting', 'Deleting')], default='active', max_length=20),
        ),
    ]
